num_epochs: 20
num_batches_per_epoch: 500
batch_size: 120
out_dim: 512
learning_rate: !!float 1e-04
alpha: 9.0
l2_weight_decay: !!float 1e-2
normalize_output: False
optimizer: 'Adam'
crop_size: 224
distance_type: 'euclidean'
dataset: 'cub200_2011'
method: 'n_pairs_mc'  # sampling method for batch construction