num_epochs: 15
num_batches_per_epoch: 500
batch_size: 120
out_dim: 256
learning_rate: !!float 6e-05
loss_l2_reg: !!float 1.5e-2
l2_weight_decay: !!float 1e-3
normalize_output: False
optimizer: 'Adam'
crop_size: 224
distance_type: 'euclidean'
dataset: 'cub200_2011'
method: 'n_pairs_mc'  # sampling method for batch construction